CREATE TABLE APPOINTMENTS (
AppointmentID INT PRIMARY KEY,
appointmentdate TIMESTAMP not null
);


CREATE TABLE EMPLOYEE (
EMPLOYEEID INT PRIMARY KEY,
FIRSTNAME VARCHAR(255),
LASTNAME VARCHAR(255),
PHONENUMBER VARCHAR(15),
ADDRESS VARCHAR(255),
SALARY  INT
);

CREATE TABLE DOCTOR (
DOCTORID INT PRIMARY KEY,
EMPLOYEEID INT references EMPLOYEE
);

CREATE TABLE RECEPTIONIST (
RECEPTIONISTID INT PRIMARY KEY,
EMPLOYEEID INT references EMPLOYEE
);

CREATE TABLE MANAGER (
MANAGERID INT PRIMARY KEY,
EMPLOYEEID INT references EMPLOYEE
);

CREATE TABLE PATIENT (
PATIENTID INT PRIMARY KEY,
FIRSTNAME VARCHAR(255) NOT NULL,
LASTNAME VARCHAR(255) NOT NULL,
PHONENUMBER VARCHAR(15),
ADDRESS VARCHAR(255) NOT NULL,
OHIP VARCHAR(255),
DOB DATE NOT NULL,
DESCRIPTION VARCHAR(255)
);

CREATE TABLE GOES_TO(
AppointmentID INT references APPOINTMENTS,
PATIENTID INT references PATIENT,
REASON VARCHAR(255),
PRIMARY KEY( APPOINTMENTID, PATIENTID)
);

CREATE TABLE ATTENDS (
DOCTORID INT references Doctor,
PATIENTID INT references Patient,
PRIMARY KEY (DOCTORID, PATIENTID)
);



CREATE TABLE PRESCRIPTIONS (
DRUGID INT PRIMARY KEY,
NAME VARCHAR(255),
DOSAGE VARCHAR(20)
);

CREATE TABLE PRESCRIBES_TO (
DRUGID INT references PRESCRIPTIONS,
PATIENTID INT references PATIENT,
PRIMARY KEY(DRUGID,PATIENTID)
);


CREATE TABLE SPECIALIST (
SPECIALISTID INT PRIMARY KEY,
FIRSTNAME VARCHAR(255),
LASTNAME VARCHAR(255),
ADDRESS VARCHAR(255),
TYPE VARCHAR(255),
PHONENUMBER VARCHAR(15)
);

CREATE TABLE REFERS_TO (
SPECIALISTID INT references SPECIALIST,
PATIENTID INT references PATIENT,
PRIMARY KEY(PATIENTID,SPECIALISTID)
);

COMMIT;
